const state={region:'',incidentRegion:'',record:{date:'',place:'',story:''},query:'',category:'全部',goal:'了解支持与咨询',draft:'',confirmed:false};
const main=document.querySelector('#main');
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let requestId=0,toastTimer;
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),4000);}
function info(html){document.querySelector('#info-content').innerHTML=html;document.querySelector('#info-dialog').showModal();}
function region(){document.querySelector('#region-dialog').showModal();}
function invalidateDraft(){state.draft='';state.confirmed=false;}
function intro(kicker,title,description){return `<div class="page-intro"><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${description}</p></div>`;}
function home(){return `<section class="hero"><div><span class="eyebrow">A LITTLE SUPPORT. AT YOUR OWN PACE.</span><h1>不必等到更强大。</h1><p>无论发生在何时、何地，你都值得获得支持。<br>不需要先想清楚一切，我们从你需要的这一小步开始。</p></div><div class="hero-aside"><p class="quote">You don’t<br>have to wait.</p><p>也不必急着做任何决定。<br>这里，允许你慢慢来。</p></div></section>
<section aria-labelledby="start-title"><div class="section-heading"><h2 id="start-title">此刻，什么对你最有帮助？</h2><span class="quiet-label">无需注册 · 随时暂停</span></div><div class="paths">
<a href="#support" class="path primary-path"><span class="path-icon" aria-hidden="true">◎</span><div><h3>我需要一些支持</h3><p>寻找医疗、情绪与生活上的帮助。</p><span class="path-tag">先照顾好此刻的自己</span></div><span class="arrow">↗</span></a>
<a href="#record" class="path"><span class="path-icon" aria-hidden="true">▤</span><div><h3>我想先记录下来</h3><p>留下记得的部分，不必一次说完。</p><span class="path-tag">只写下你愿意写的</span></div><span class="arrow">↗</span></a>
<a href="#support?category=legal" class="path"><span class="path-icon" aria-hidden="true">◷</span><div><h3>我想了解有哪些选择</h3><p>从所在地出发，了解可能的求助路径。</p><span class="path-tag">了解，不等于必须行动</span></div><span class="arrow">↗</span></a>
<a href="#action" class="path"><span class="path-icon" aria-hidden="true">↗</span><div><h3>我准备好迈出下一步</h3><p>整理材料、准备表达，减少反复讲述。</p><span class="path-tag">每一步都由你确认</span></div><span class="arrow">↗</span></a>
</div></section><div class="lower-grid"><section class="prepare-box"><span class="eyebrow">IT’S OKAY TO TAKE YOUR TIME</span><h3 style="margin-top:9px">还没准备好讲述？也没关系。</h3><p>不必给经历下定义，也不需要证明自己的感受。<br>你可以只看看，或者先让自己缓一缓。</p><button class="small-link" id="grounding">给自己片刻空间 →</button></section><section class="principles" aria-label="你的选择"><div class="principle"><span class="check">✓</span><div><strong>你的经历，由你掌握</strong><p>演示内容仅在当前页面内存中保留。</p></div></div><div class="principle"><span class="check">✓</span><div><strong>你的选择，始终被尊重</strong><p>可以跳过、暂停，也可以改变主意。</p></div></div><div class="principle"><span class="check">✓</span><div><strong>支持，不以报案为前提</strong><p>先照顾自己，也是一种行动。</p></div></div></section></div>`;}
function support(){return `${intro('FIND YOUR SUPPORT','你不必独自面对。','从你现在需要的帮助开始。选择地区，探索适合自己的支持方式。')}<div class="demo-note">演示资源 · ${escapeHTML(state.region||'尚未选择地区')}。以下均为服务类型占位，不是真实机构、紧急服务或已验证的当地建议。</div><form id="search-form" class="search-row"><input id="search-input" aria-label="搜索支持" placeholder="例如：心理、医疗、法律咨询、请假" value="${escapeHTML(state.query)}"><button class="primary">搜索支持</button></form><div class="chips" aria-label="支持类别">${['全部','情绪支持','医疗帮助','法律咨询','生活支持'].map(c=>`<button class="chip ${state.category===c?'selected':''}" aria-pressed="${state.category===c}" data-category="${c}">${c}</button>`).join('')}</div><div class="section-heading"><h2>可以从这些支持开始</h2><button class="text-button" id="change-region">更改地区 ↗</button></div><div class="resource-grid" id="resources" aria-live="polite" aria-busy="true"><div class="empty">正在整理演示资源…</div></div><button class="small-link" id="urgent">如果你现在不安全 →</button>`;}
async function loadResources(){const current=++requestId;try{const rows=await supportAPI.searchResources(state);if(current!==requestId||!document.querySelector('#resources'))return;const box=document.querySelector('#resources');box.setAttribute('aria-busy','false');box.innerHTML=rows.length?rows.map(r=>`<article class="resource-card"><span class="eyebrow">${r.kind} · ${r.category}</span><h3>${r.title}</h3><p>${r.description}</p><div class="resource-meta">${r.tags.map(t=>`<span>${t}</span>`).join('')}</div><button class="small-link" data-resource="${r.id}">了解这类帮助 →</button></article>`).join(''):'<div class="empty"><h3>没有找到匹配的演示资源</h3><p>试试“医疗”“法律”或清除筛选。</p><button id="reset-search" class="small-link">显示全部支持 →</button></div>';box.querySelectorAll('[data-resource]').forEach(b=>b.onclick=()=>resourceInfo(rows.find(r=>r.id===b.dataset.resource)));document.querySelector('#reset-search')?.addEventListener('click',()=>{state.query='';state.category='全部';render();});}catch{if(current===requestId){const box=document.querySelector('#resources');if(box){box.setAttribute('aria-busy','false');box.innerHTML='<div class="empty">暂时无法显示资源，请重新搜索。</div>';}}}}
function resourceInfo(r){info(`<span class="status-pill">演示占位 · 未接入机构</span><h2>${r.title}</h2><p>${r.description}</p><ul class="dialog-list"><li>当前地区：${escapeHTML(state.region||'未选择')}</li><li>接入后会显示：真实名称、联系方式、费用、语言、开放时间与核验日期。</li><li>此页面不会拨打电话、预约或转交信息。</li></ul><button class="primary" id="resource-next">准备一份${r.id==='daily'?'生活安排请求':'咨询草稿'} →</button>`);document.querySelector('#resource-next').onclick=()=>{state.goal=r.id==='daily'?'申请生活安排调整':'了解支持与咨询';invalidateDraft();document.querySelector('#info-dialog').close();location.hash='action';};}
function record(){return `${intro('YOUR WORDS, YOUR PACE','先留下你记得的部分。','不需要完整、按顺序或使用法律术语。“不记得”和“暂时不想说”都可以。')}<div class="form-layout"><form id="record-form" class="panel"><h3>我的记录</h3><div class="form-pair"><div><label for="event-date">大致时间（可选）</label><input id="event-date" placeholder="例如：上周，或记不清" value="${escapeHTML(state.record.date)}"></div><div><label for="event-place">发生地点（可选）</label><input id="event-place" placeholder="只填写你愿意分享的部分" value="${escapeHTML(state.record.place)}"></div></div><label for="event-story">你想记录的内容（可选）</label><textarea id="event-story" placeholder="可以是发生了什么、你记得的话，或此刻想留下的任何信息。">${escapeHTML(state.record.story)}</textarea><p class="note">不会上传或自动保存到设备。刷新、关闭或快速离开会清除当前记录。请勿在演示中输入真实身份信息。</p><div class="button-row"><button class="primary" type="submit">用这份记录准备下一步 →</button><button type="button" class="secondary" id="export-record">下载我的记录</button><button type="button" class="text-button" id="clear-record">清除记录</button></div></form><aside class="panel side-panel"><span class="eyebrow">A GENTLE REMINDER</span><h3 style="margin-top:12px">你无需在这里证明什么。</h3><p>即使没有完整材料，也可以先了解支持。</p><ul><li>保留自己的原始表达。</li><li>不确定的地方可以留空。</li><li>记录不代表决定投诉或报案。</li></ul><p class="note">下载会在设备上留下文件。请先确认这台设备适合保存你的记录。</p></aside></div>`;}
function action(){return `${intro('ONE STEP AT A TIME','下一步，也可以很小。','先准备，再决定。你可以随时修改目标或返回记录。')}<div class="demo-note">材料生成使用固定模板。没有法律判断、当地程序核验或真实提交。</div><div class="form-layout"><section class="panel"><h3>你希望先做什么？</h3><label for="goal">选择这一步的目标</label><select id="goal">${['了解支持与咨询','准备投诉或报案咨询','申请生活安排调整'].map(g=>`<option value="${g}" ${state.goal===g?'selected':''}>${g}</option>`).join('')}</select><p class="note">${state.record.story?'已带入你在本次会话中填写的记录。':'没有记录也可以准备咨询草稿，不必现在讲述经历。'}</p><button id="generate" class="primary">${state.draft?'重新生成演示草稿':'生成演示草稿'} →</button><div id="draft-section">${state.draft?draftMarkup():''}</div></section><aside class="panel side-panel"><h3>这一步怎么进行</h3><div class="step"><span class="step-number">1</span><div><strong>选择你的目标</strong><p>不用一次处理所有事情。</p></div></div><div class="step"><span class="step-number">2</span><div><strong>核对与修改草稿</strong><p>确认它准确表达了你的意思。</p></div></div><div class="step"><span class="step-number">3</span><div><strong>决定是否使用</strong><p>演示可下载材料，不会向外发送。</p></div></div><a class="small-link" href="#record">返回修改原始记录 →</a></aside></div>`;}
function draftMarkup(){return `<label for="draft-text">可编辑草稿</label><textarea id="draft-text" style="min-height:300px">${escapeHTML(state.draft)}</textarea><label class="check-label"><input type="checkbox" id="confirm-draft" ${state.confirmed?'checked':''}>我已核对草稿，理解这是演示，不会真实提交。</label><div class="button-row"><button class="secondary" id="download-draft">下载草稿</button><button class="primary" id="simulate" ${state.confirmed?'':'disabled'}>预览提交结果</button></div>`;}
function bindDraft(){document.querySelector('#draft-text')?.addEventListener('input',e=>{state.draft=e.target.value;state.confirmed=false;document.querySelector('#confirm-draft').checked=false;document.querySelector('#simulate').disabled=true;});document.querySelector('#confirm-draft')?.addEventListener('change',e=>{state.confirmed=e.target.checked;document.querySelector('#simulate').disabled=!state.confirmed;});document.querySelector('#download-draft')?.addEventListener('click',()=>download(window.uiLanguage==='en'?'inquiry-draft.txt':'咨询草稿.txt',state.draft));document.querySelector('#simulate')?.addEventListener('click',async e=>{if(!state.confirmed)return;e.target.disabled=true;try{await supportAPI.simulateSubmission();info('<span class="status-pill">模拟结束 · 未发送</span><h2>你的材料已准备好。</h2><p>这只是提交结果预览。没有联系任何机构，没有产生真实回执，也不代表受理。</p><p style="margin-top:14px">接入真实服务后，此处将显示接收机构、提交时间、回执与后续安排。</p>');}catch{toast('模拟暂时失败，请重试。');}finally{if(document.querySelector('#simulate'))document.querySelector('#simulate').disabled=!state.confirmed;}});}
function download(name,text){if(!text.trim()){toast('还没有可下载的内容。');return;}const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已准备下载。文件会保留在你的设备上。');}
function render(){requestId++;const route=location.hash.slice(1).split('?')[0]||'home';const valid=['home','support','record','action'].includes(route)?route:'home';document.querySelectorAll('[data-nav]').forEach(a=>{a.classList.toggle('active',a.dataset.nav===valid);if(a.dataset.nav===valid)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});main.innerHTML=({home,support,record,action}[valid])();document.title=`${{home:'从这里开始',support:'寻找支持',record:'记录我的经历',action:'我的下一步'}[valid]} · 此刻`;
 document.querySelector('#grounding')?.addEventListener('click',()=>info('<h2>先把注意力放回此刻。</h2><p>如果你愿意，可以感受脚下的地面，看看周围，找到一件让你感觉平静的东西。不需要做得“正确”，不舒服就停下来。</p><div class="breathing">现在，不必解决所有事情。</div><p>这不是治疗，也不会代替专业支持。你可以随时关闭这里。</p>'));
 if(valid==='support'){document.querySelector('#search-form').onsubmit=e=>{e.preventDefault();state.query=document.querySelector('#search-input').value;render();};document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{state.query=document.querySelector('#search-input').value;state.category=b.dataset.category;render();});document.querySelector('#change-region').onclick=region;document.querySelector('#urgent').onclick=()=>info('<h2>如果你现在不安全</h2><p>如果能够安全离开，可以先到有人值守或能提供帮助的地方，联系可信任的人，或当地紧急服务。</p><p style="margin-top:14px">本演示没有接入紧急呼叫或核实各地号码，不能提供实时救援。</p>');loadResources();}
 if(valid==='record'){for(const [id,key] of [['event-date','date'],['event-place','place'],['event-story','story']])document.getElementById(id).oninput=e=>{state.record[key]=e.target.value;invalidateDraft();};document.querySelector('#record-form').onsubmit=e=>{e.preventDefault();location.hash='action';};document.querySelector('#export-record').onclick=()=>{if(!Object.values(state.record).some(v=>v.trim())){toast('还没有记录，可以先写下愿意留下的部分。');return;}download(window.uiLanguage==='en'?'my-record.txt':'我的记录.txt',(window.uiLanguage==='en'?`My original record\nTime: ${state.record.date}\nLocation: ${state.record.place}\n\n${state.record.story}`:`我的原始记录\n时间：${state.record.date}\n地点：${state.record.place}\n\n${state.record.story}`));};document.querySelector('#clear-record').onclick=()=>{info('<h2>清除当前记录？</h2><p>这会清除本次会话的记录和生成草稿，无法恢复。已经下载的文件不会被删除。</p><div class="button-row"><button class="secondary" id="keep-record">保留记录</button><button class="primary" id="confirm-clear">清除记录</button></div>');document.querySelector('#keep-record').onclick=()=>document.querySelector('#info-dialog').close();document.querySelector('#confirm-clear').onclick=()=>{state.record={date:'',place:'',story:''};invalidateDraft();document.querySelector('#info-dialog').close();render();toast('当前记录和草稿已清除。');};};}
 if(valid==='action'){document.querySelector('#goal').onchange=e=>{state.goal=e.target.value;invalidateDraft();render();};document.querySelector('#generate').onclick=async e=>{const button=e.target;button.disabled=true;button.textContent='正在准备演示草稿…';const snapshot=JSON.stringify({record:state.record,region:state.region,incidentRegion:state.incidentRegion,goal:state.goal});try{const draft=await supportAPI.prepareDraft(JSON.parse(snapshot));if(snapshot!==JSON.stringify({record:state.record,region:state.region,incidentRegion:state.incidentRegion,goal:state.goal}))return;state.draft=draft;state.confirmed=false;if(location.hash.split('?')[0]==='#action'){render();document.querySelector('#draft-text')?.focus();}}catch{toast('草稿生成失败，请重试。');}finally{if(button.isConnected){button.disabled=false;button.textContent='生成演示草稿 →';}}};bindDraft();}
}
document.querySelector('#region-button').onclick=region;
document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
document.querySelector('#region-form').onsubmit=e=>{e.preventDefault();state.region=document.querySelector('#current-region').value;state.incidentRegion=document.querySelector('#incident-region').value;invalidateDraft();document.querySelector('#region-label').textContent=state.region||'选择所在地';document.querySelector('#region-dialog').close();render();toast('地区已更新。当前资源仍为演示占位。');};
document.querySelectorAll('.privacy-button').forEach(b=>b.onclick=()=>info('<h2>关于这个演示</h2><p>这是纯前端原型。搜索、生成与提交均为模拟，没有账户、服务器存储、分析追踪或真实 API 请求。</p><ul class="dialog-list"><li>输入仅保留在当前页面内存中，刷新或关闭会丢失。</li><li>下载的文件会留在你的设备上。</li><li>快速离开会清除当前输入，并跳转到普通网页，但不会清除浏览历史或已下载文件。</li><li>所有机构卡片都是占位信息，不能用于实际联系或紧急救援。</li></ul>'));
document.querySelector('#quick-exit').onclick=()=>{state.record={date:'',place:'',story:''};state.region='';state.incidentRegion='';state.query='';invalidateDraft();document.querySelectorAll('dialog[open]').forEach(d=>d.close());document.querySelectorAll('input,textarea').forEach(el=>el.value='');main.replaceChildren();location.replace('https://www.wikipedia.org/');};
window.addEventListener('pagehide',()=>{state.record={date:'',place:'',story:''};invalidateDraft();document.querySelectorAll('input,textarea').forEach(el=>el.value='');});
window.addEventListener('pageshow',e=>{if(e.persisted)render();});
window.addEventListener('hashchange',()=>{if(location.hash.includes('category=legal')){state.category='法律咨询';state.query='';}render();main.focus({preventScroll:true});window.scrollTo(0,0);});
if(location.hash.includes('category=legal'))state.category='法律咨询';render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'navigate_support_workspace',description:'Open a public section of the prototype. Does not read or submit private records.',inputSchema:{type:'object',properties:{section:{type:'string',enum:['home','support','record','action']}},required:['section'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||Object.keys(input).some(k=>k!=='section')||!['home','support','record','action'].includes(input.section))throw new Error('Invalid section');history.replaceState(null,'',`#${input.section}`);render();return {section:input.section,simulation:true};}})).catch(()=>{});}catch{}}
