const state={region:'',incidentRegion:'',record:{date:'',place:'',story:''},resourceRegion:'',query:'',category:'全部',goal:'准备投诉或报案咨询',draft:'',confirmed:false};
const main=document.querySelector('#main');
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let requestId=0,toastTimer;
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),4000);}
function info(html){document.querySelector('#info-content').innerHTML=html;document.querySelector('#info-dialog').showModal();}
function region(){document.querySelector('#region-dialog').showModal();}
function invalidateDraft(){state.draft='';state.confirmed=false;}
function intro(kicker,title,description){return `<div class="page-intro"><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${description}</p></div>`;}
function home(){return `<section class="hero action-hero"><div><span class="eyebrow">SUPPORT THAT HELPS YOU ACT</span><h1>不必等自己准备好了，才开始维权。</h1><p>你不需要先整理好情绪、完整回忆经历，或弄懂所有程序。<br>从你现在能提供的信息开始，让系统分担整理和准备的工作。</p><a href="#action" class="primary hero-cta">帮我开始维权 →</a><p class="note">当前为流程演示，不会真实报案或联系机构。</p></div><div class="hero-aside"><p class="quote">You don’t<br>have to wait.</p><p>把繁琐交给系统。<br>把决定留给你。</p></div></section>
<section class="automation-strip" aria-label="自动化流程"><div><span>01</span><strong>从零散信息开始</strong><p>不必现在讲完整。</p></div><div><span>02</span><strong>系统协助准备</strong><p>已有信息复用，未知保持留白。</p></div><div><span>03</span><strong>由你确认下一步</strong><p>披露与提交需要你的授权。</p></div></section>
<section aria-labelledby="start-title"><div class="section-heading"><h2 id="start-title">不用独自承担每一道程序。</h2><span class="quiet-label">无需注册 · 不要求完整叙述</span></div><div class="paths">
<a href="#action" class="path primary-path"><span class="path-icon" aria-hidden="true">↗</span><div><h3>帮我准备报案或投诉</h3><p>先生成咨询材料，不必先完成整段叙述。</p><span class="path-tag">从能做到的部分开始</span></div><span class="arrow">↗</span></a>
<a href="#record" class="path"><span class="path-icon" aria-hidden="true">▤</span><div><h3>我只能提供一些片段</h3><p>一句话、一个时间或地点，都可以先记下。</p><span class="path-tag">不补写、不推断你的记忆</span></div><span class="arrow">↗</span></a>
<a href="#support?category=legal" class="path"><span class="path-icon" aria-hidden="true">◷</span><div><h3>哪些事项需要尽早核实？</h3><p>了解渠道咨询入口，准备询问程序与时间要求。</p><span class="path-tag">演示不计算法律期限</span></div><span class="arrow">↗</span></a>
<a href="#support" class="path"><span class="path-icon" aria-hidden="true">◎</span><div><h3>我也需要照顾和支持</h3><p>医疗、情绪和生活支持，始终可以单独选择。</p><span class="path-tag">无需决定报案也能寻找帮助</span></div><span class="arrow">↗</span></a>
</div></section><div class="lower-grid"><section class="prepare-box"><span class="eyebrow">LESS TO CARRY</span><h3 style="margin-top:9px">还没准备好，不应成为求助的门槛。</h3><p>整理材料和查找程序不该全部压在你身上。<br>你可以先开始准备，也可以暂停或改变方向。</p><button class="small-link" id="grounding">需要的话，先给自己片刻空间 →</button></section><section class="principles" aria-label="你的选择"><div class="principle"><span class="check">✓</span><div><strong>减少反复讲述</strong><p>复用你已经确认的内容。</p></div></div><div class="principle"><span class="check">✓</span><div><strong>决定权始终在你手里</strong><p>准备材料不等于同意对外提交。</p></div></div><div class="principle"><span class="check">✓</span><div><strong>明确知道流程走到哪里</strong><p>草稿、发送和受理是不同状态。</p></div></div></section></div>`;}

function support(){const chosen=state.resourceRegion||state.region;return `${intro('LOCAL RESOURCES','按地区寻找维权与支持资源。','查找官方和专业机构入口。资源检索不需要提供经历或身份信息。')}<div class="demo-note">这是人工整理的部分资源，不是全部机构名单。官网内容已核对，实际可用性、资格、语言与费用仍需向机构确认。</div><label for="resource-region">搜索地区</label><select id="resource-region"><option value="">请选择地区</option>${resourceRegions.map(r=>`<option value="${r}" ${normalizeResourceRegion(chosen)===r?'selected':''}>${r}</option>`).join('')}<option value="global" ${chosen&&normalizeResourceRegion(chosen)==='global'?'selected':''}>全球目录 / 其他地区</option></select><div class="button-row"><button class="secondary" id="use-current">使用当前所在地</button><button class="secondary" id="use-incident">使用事件发生地</button><button class="text-button" id="change-region">更改地区 ↗</button></div>${!chosen?'<p class="note">请先选择地区。暂时显示全球目录，不会自动推断你的所在地。</p>':normalizeResourceRegion(chosen)==='global'?'<p class="note">该地区暂无专门条目，以下为全球目录入口。请在目录中进一步查找。</p>':''}<form id="search-form" class="search-row" style="margin-top:22px"><input id="search-input" aria-label="搜索支持" placeholder="例如：心理、医疗、法律咨询、请假" value="${escapeHTML(state.query)}"><button class="primary">搜索支持</button></form><div class="chips" aria-label="支持类别">${['全部','报案渠道','法律咨询','情绪支持','医疗帮助','资源目录'].map(c=>`<button class="chip ${state.category===c?'selected':''}" aria-pressed="${state.category===c}" data-category="${c}">${c}</button>`).join('')}</div><div class="section-heading"><h2>已收录资源</h2><span id="result-count" class="quiet-label" aria-live="polite"></span></div><div class="resource-grid" id="resources" aria-live="polite" aria-busy="true"></div><button class="small-link" id="urgent">如果你现在不安全 →</button>`;}
async function loadResources(){const current=++requestId;try{const rows=await supportAPI.searchResources({...state,region:state.resourceRegion||state.region});if(current!==requestId||!document.querySelector('#resources'))return;const box=document.querySelector('#resources');box.setAttribute('aria-busy','false');document.querySelector('#result-count').innerHTML=`<span>${rows.length}</span> <span>条匹配结果</span>`;box.innerHTML=rows.length?rows.map(r=>`<article class="resource-card"><span class="eyebrow">${escapeHTML(r.category)}</span><h3>${escapeHTML(r.name)}</h3><p>${escapeHTML(r.desc)}</p><div class="resource-meta"><span>${r.region==='global'?'全球目录':escapeHTML(r.region)}</span></div><p class="note">${escapeHTML(r.scope)}</p><p class="note"><span>官网信息核对</span> · ${r.checked}</p><a class="small-link" href="${escapeHTML(r.url)}" target="_blank" rel="noopener noreferrer">查看机构官网 ↗</a><br><button class="small-link" data-resource="${r.id}">查看范围与下一步</button></article>`).join(''):'<div class="empty"><h3>没有匹配的已收录资源</h3><p>试试其他关键词或显示全部类别；没有结果不代表当地没有服务。</p><button id="reset-search" class="small-link">显示全部支持 →</button></div>';box.querySelectorAll('[data-resource]').forEach(b=>b.onclick=()=>resourceInfo(rows.find(r=>r.id===b.dataset.resource)));document.querySelector('#reset-search')?.addEventListener('click',()=>{state.query='';state.category='全部';render();});}catch{if(current===requestId){const box=document.querySelector('#resources');if(box){box.setAttribute('aria-busy','false');box.innerHTML='<div class="empty">暂时无法显示资源，请重新搜索。</div>';}}}}
function resourceInfo(r){info(`<span class="status-pill">来源已核对 · 非实时可用性保证</span><h2>${escapeHTML(r.name)}</h2><p>${escapeHTML(r.desc)}</p><h3 style="margin-top:18px">适用范围</h3><p>${escapeHTML(r.scope)}</p><p class="note"><span>官网信息核对</span> · ${r.checked}</p><a class="small-link" href="${escapeHTML(r.url)}" target="_blank" rel="noopener noreferrer">查看机构官网 ↗</a><p class="note">打开官网不会自动发送你的记录。外部网站有自己的隐私政策。</p><button class="primary" id="resource-next">准备咨询草稿 →</button><p class="note">生成草稿不会联系这个机构；请自行核对接收渠道。</p>`);document.querySelector('#resource-next').onclick=()=>{state.goal='了解支持与咨询';invalidateDraft();document.querySelector('#info-dialog').close();location.hash='action';};}
function record(){return `${intro('YOUR WORDS, YOUR PACE','只记得一点，也可以开始。','不必主动回忆更多。写下现在愿意提供的片段，系统会在准备材料时复用，不要求你重新讲述。')}<div class="form-layout"><form id="record-form" class="panel"><h3>我的记录</h3><div class="form-pair"><div><label for="event-date">大致时间（可选）</label><input id="event-date" placeholder="例如：上周，或记不清" value="${escapeHTML(state.record.date)}"></div><div><label for="event-place">发生地点（可选）</label><input id="event-place" placeholder="只填写你愿意分享的部分" value="${escapeHTML(state.record.place)}"></div></div><label for="event-story">你想记录的内容（可选）</label><textarea id="event-story" placeholder="可以是发生了什么、你记得的话，或此刻想留下的任何信息。">${escapeHTML(state.record.story)}</textarea><p class="note">不会上传或自动保存到设备。刷新或关闭会清除当前记录。请勿在演示中输入真实身份信息。</p><div class="button-row"><button class="primary" type="submit">用这份记录准备下一步 →</button><button type="button" class="secondary" id="export-record">下载我的记录</button><button type="button" class="text-button" id="clear-record">清除记录</button></div></form><aside class="panel side-panel"><span class="eyebrow">A GENTLE REMINDER</span><h3 style="margin-top:12px">你无需在这里证明什么。</h3><p>即使没有完整材料，也可以先了解支持。</p><ul><li>保留自己的原始表达。</li><li>不确定的地方可以留空。</li><li>记录不代表决定投诉或报案。</li></ul><p class="note">下载会在设备上留下文件。请先确认这台设备适合保存你的记录。</p></aside></div>`;}
function action(){return `${intro('LET’S TAKE SOME OF THE WORK OFF YOUR SHOULDERS','不必准备好一切，才能开始。','不要求先完整回忆。我们用已有信息准备草稿，尚未提供的内容保持留白。')}<div class="demo-note">资源链接是真实机构入口；草稿生成与提交仍为模拟。</div><div class="form-layout"><section class="panel"><div class="section-heading"><h3>先启动准备</h3><span class="status-pill">${state.draft?'草稿已准备 · 未提交':'准备阶段 · 未提交'}</span></div><div class="setup-location"><strong>当地流程从事件发生地开始</strong><p>${escapeHTML(state.incidentRegion||'事件地区尚未提供')}</p><button type="button" class="small-link" id="action-region">选择或修改地区 →</button></div><label for="goal">这次希望系统协助什么？</label><select id="goal">${['准备投诉或报案咨询','了解支持与咨询','申请生活安排调整'].map(g=>`<option value="${g}" ${state.goal===g?'selected':''}>${g}</option>`).join('')}</select><div class="record-summary"><strong>你已提供的信息</strong><ul><li>${state.record.date?'已提供大致时间':'时间：暂未提供'}</li><li>${state.record.place?'已提供地点':'地点：暂未提供'}</li><li>${state.record.story?'已提供原始片段，将原样带入草稿':'经历：暂不讲述也可以'}</li></ul><a href="#record" class="small-link">补充一点信息（可跳过） →</a></div><p class="note">无需填写更多也能生成咨询草稿。不会自动推断事实或认定法律性质。</p><button id="generate" class="primary">${state.draft?'重新生成演示草稿':'生成演示草稿'} →</button><div id="draft-section">${state.draft?draftMarkup():''}</div></section><aside class="panel side-panel"><h3>系统协助，你来决定</h3><div class="step"><span class="step-number">1</span><div><strong>整理已有信息</strong><p>${state.draft?'已带入草稿，不补写未知细节。':'使用已有记录，无需重复输入。'}</p></div></div><div class="step"><span class="step-number">2</span><div><strong>核实渠道与时间要求</strong><p>官方资源已接入 · 具体渠道适用性与时间要求仍需核实。</p></div></div><div class="step"><span class="step-number">3</span><div><strong>准备材料并核对</strong><p>${state.draft?'草稿可编辑，请核对表达与披露范围。':'可演示 · 生成可编辑的咨询草稿。'}</p></div></div><div class="step"><span class="step-number">4</span><div><strong>授权后提交与跟进</strong><p>待接入 · 当前只预览，不会发送或产生回执。</p></div></div><a class="small-link" href="#support">查看当地资源 →</a><div class="timing-note"><strong>时间事项，需要具体核实。</strong><p>报案、投诉、诉讼和证据保留分别核实。这里没有验证当地期限，不应将演示当作时间建议。</p></div></aside></div>`;}
function draftMarkup(){return `<label for="draft-text">可编辑草稿</label><textarea id="draft-text" style="min-height:300px">${escapeHTML(state.draft)}</textarea><label class="check-label"><input type="checkbox" id="confirm-draft" ${state.confirmed?'checked':''}>我已核对草稿，理解这是演示，不会真实提交。</label><div class="button-row"><button class="secondary" id="download-draft">下载草稿</button><button class="primary" id="simulate" ${state.confirmed?'':'disabled'}>预览提交结果</button></div>`;}
function bindDraft(){document.querySelector('#draft-text')?.addEventListener('input',e=>{state.draft=e.target.value;state.confirmed=false;document.querySelector('#confirm-draft').checked=false;document.querySelector('#simulate').disabled=true;});document.querySelector('#confirm-draft')?.addEventListener('change',e=>{state.confirmed=e.target.checked;document.querySelector('#simulate').disabled=!state.confirmed;});document.querySelector('#download-draft')?.addEventListener('click',()=>download(window.uiLanguage==='en'?'inquiry-draft.txt':'咨询草稿.txt',state.draft));document.querySelector('#simulate')?.addEventListener('click',async e=>{if(!state.confirmed)return;e.target.disabled=true;try{await supportAPI.simulateSubmission();info('<span class="status-pill">模拟结束 · 未发送</span><h2>你的材料已准备好。</h2><p>这只是提交结果预览。没有联系任何机构，没有产生真实回执，也不代表受理。</p><p style="margin-top:14px">接入真实服务后，此处将显示接收机构、提交时间、回执与后续安排。</p>');}catch{toast('模拟暂时失败，请重试。');}finally{if(document.querySelector('#simulate'))document.querySelector('#simulate').disabled=!state.confirmed;}});}
function download(name,text){if(!text.trim()){toast('还没有可下载的内容。');return;}const url=URL.createObjectURL(new Blob(['\ufeff'+text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已准备下载。文件会保留在你的设备上。');}
function render(){requestId++;const route=location.hash.slice(1).split('?')[0]||'home';const valid=['home','support','record','action'].includes(route)?route:'home';document.querySelectorAll('[data-nav]').forEach(a=>{a.classList.toggle('active',a.dataset.nav===valid);if(a.dataset.nav===valid)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});main.innerHTML=({home,support,record,action}[valid])();document.title=`${{home:'从这里开始',support:'寻找支持',record:'记录我的经历',action:'我的下一步'}[valid]} · 此刻`;
 document.querySelector('#grounding')?.addEventListener('click',()=>info('<h2>先把注意力放回此刻。</h2><p>如果你愿意，可以感受脚下的地面，看看周围，找到一件让你感觉平静的东西。不需要做得“正确”，不舒服就停下来。</p><div class="breathing">现在，不必解决所有事情。</div><p>这不是治疗，也不会代替专业支持。你可以随时关闭这里。</p>'));
 if(valid==='support'){document.querySelector('#resource-region').onchange=e=>{state.resourceRegion=e.target.value||'global';state.query='';state.category='全部';render();};for(const [id,key] of [['use-current','region'],['use-incident','incidentRegion']])document.getElementById(id).onclick=()=>{if(!state[key]){toast(key==='region'?'先选择当前所在地，再使用这个选项。':'先填写事件发生地，再使用这个选项。');region();return;}state.resourceRegion=normalizeResourceRegion(state[key]);state.query='';state.category='全部';render();if(state.resourceRegion==='global')toast('地区无法精确匹配，已显示全球目录。');};document.querySelector('#search-form').onsubmit=e=>{e.preventDefault();state.query=document.querySelector('#search-input').value;render();};document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{state.query=document.querySelector('#search-input').value;state.category=b.dataset.category;render();});document.querySelector('#change-region').onclick=region;document.querySelector('#urgent').onclick=()=>info('<h2>如果你现在不安全</h2><p>如果能够安全离开，可以先到有人值守或能提供帮助的地方，联系可信任的人，或当地紧急服务。</p><p style="margin-top:14px">本演示没有接入紧急呼叫或核实各地号码，不能提供实时救援。</p>');loadResources();}
 if(valid==='record'){for(const [id,key] of [['event-date','date'],['event-place','place'],['event-story','story']])document.getElementById(id).oninput=e=>{state.record[key]=e.target.value;invalidateDraft();};document.querySelector('#record-form').onsubmit=e=>{e.preventDefault();location.hash='action';};document.querySelector('#export-record').onclick=()=>{if(!Object.values(state.record).some(v=>v.trim())){toast('还没有记录，可以先写下愿意留下的部分。');return;}download(window.uiLanguage==='en'?'my-record.txt':'我的记录.txt',(window.uiLanguage==='en'?`My original record\nTime: ${state.record.date}\nLocation: ${state.record.place}\n\n${state.record.story}`:`我的原始记录\n时间：${state.record.date}\n地点：${state.record.place}\n\n${state.record.story}`));};document.querySelector('#clear-record').onclick=()=>{info('<h2>清除当前记录？</h2><p>这会清除本次会话的记录和生成草稿，无法恢复。已经下载的文件不会被删除。</p><div class="button-row"><button class="secondary" id="keep-record">保留记录</button><button class="primary" id="confirm-clear">清除记录</button></div>');document.querySelector('#keep-record').onclick=()=>document.querySelector('#info-dialog').close();document.querySelector('#confirm-clear').onclick=()=>{state.record={date:'',place:'',story:''};invalidateDraft();document.querySelector('#info-dialog').close();render();toast('当前记录和草稿已清除。');};};}
 if(valid==='action'){document.querySelector('#action-region').onclick=region;document.querySelector('#goal').onchange=e=>{state.goal=e.target.value;invalidateDraft();render();};document.querySelector('#generate').onclick=async e=>{const button=e.target;button.disabled=true;button.textContent='正在准备演示草稿…';const snapshot=JSON.stringify({record:state.record,region:state.region,incidentRegion:state.incidentRegion,goal:state.goal});try{const draft=await supportAPI.prepareDraft(JSON.parse(snapshot));if(snapshot!==JSON.stringify({record:state.record,region:state.region,incidentRegion:state.incidentRegion,goal:state.goal}))return;state.draft=draft;state.confirmed=false;if(location.hash.split('?')[0]==='#action'){render();document.querySelector('#draft-text')?.focus();}}catch{toast('草稿生成失败，请重试。');}finally{if(button.isConnected){button.disabled=false;button.textContent='生成演示草稿 →';}}};bindDraft();}
}
document.querySelector('#region-button').onclick=region;
document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
document.querySelector('#region-form').onsubmit=e=>{e.preventDefault();state.region=document.querySelector('#current-region').value;state.resourceRegion='';state.incidentRegion=document.querySelector('#incident-region').value;invalidateDraft();document.querySelector('#region-label').textContent=state.region||'选择所在地';document.querySelector('#region-dialog').close();render();toast('已更新地区，将筛选相应资源。');};
document.querySelectorAll('.privacy-button').forEach(b=>b.onclick=()=>info('<h2>关于这个演示</h2><p>资源链接是真实机构入口；草稿生成与提交仍为模拟。</p><ul class="dialog-list"><li>输入仅保留在当前页面内存中，刷新或关闭会丢失。</li><li>下载的文件会留在你的设备上。</li><li>GoatCounter 基础统计默认开启，可在页脚关闭，并尊重浏览器 DNT/GPC。不发送记录、搜索或地区选择。服务会接收网络与设备信息；公开展示汇总计数，可在页脚停止。</li><li>资源页提供真实机构链接，但不是完整名单或实时服务保证。</li></ul>'));
window.addEventListener('pagehide',()=>{state.record={date:'',place:'',story:''};invalidateDraft();document.querySelectorAll('input,textarea').forEach(el=>el.value='');});
window.addEventListener('pageshow',e=>{if(e.persisted)render();});
window.addEventListener('hashchange',()=>{if(location.hash.includes('category=legal')){state.category='法律咨询';state.query='';}render();main.focus({preventScroll:true});window.scrollTo(0,0);});
if(location.hash.includes('category=legal'))state.category='法律咨询';render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'navigate_support_workspace',description:'Open a public section of the prototype. Does not read or submit private records.',inputSchema:{type:'object',properties:{section:{type:'string',enum:['home','support','record','action']}},required:['section'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||Object.keys(input).some(k=>k!=='section')||!['home','support','record','action'].includes(input.section))throw new Error('Invalid section');history.replaceState(null,'',`#${input.section}`);render();return {section:input.section,simulation:true};}})).catch(()=>{});}catch{}}
