/* Curated source directory. Reviewed 2026-09-23. Not an exhaustive or live service registry. */
window.resourceDirectory=[
  {
    "id": "cn-law",
    "region": "中国大陆",
    "category": "法律咨询",
    "name": "中国法律服务网 · 12348",
    "enName": "China Public Legal Service · 12348",
    "desc": "查询公共法律服务机构、办事指南与咨询入口。",
    "enDesc": "Find public legal service organizations, guidance and consultation options.",
    "scope": "中国大陆；具体法律援助条件需向当地机构确认。",
    "enScope": "Mainland China; confirm local legal-aid eligibility with the provider.",
    "url": "https://www.12348.gov.cn/",
    "checked": "2026-09-23"
  },
  {
    "id": "cn-gd",
    "region": "中国大陆",
    "category": "法律咨询",
    "name": "广东省妇联 · 12338 服务平台",
    "enName": "Guangdong Women’s Federation · 12338",
    "desc": "广东省妇女维权咨询服务入口。",
    "enDesc": "Entry point for women’s rights consultation in Guangdong.",
    "scope": "广东省；不是全国统一线上受理入口。",
    "enScope": "Guangdong only; not a nationwide online intake service.",
    "url": "https://www.gdwomen.org.cn/12338/",
    "checked": "2026-09-23"
  },
  {
    "id": "hk-rain",
    "region": "香港特别行政区",
    "category": "情绪支持",
    "name": "风雨兰 · 性暴力支持",
    "enName": "RainLily · Sexual violence support",
    "desc": "性暴力支援、法律咨询及陪伴服务信息。",
    "enDesc": "Information on sexual violence support, legal consultation and accompaniment.",
    "scope": "主要面向年满 14 岁的女性性暴力经历者；其他服务条件请咨询机构。",
    "enScope": "Primarily female survivors aged 14 or above; confirm eligibility for individual services.",
    "url": "https://rainlily.org.hk/",
    "checked": "2026-09-23"
  },
  {
    "id": "hk-eoc",
    "region": "香港特别行政区",
    "category": "法律咨询",
    "name": "平等机会委员会 · COMPASS",
    "enName": "Equal Opportunities Commission · COMPASS",
    "desc": "性骚扰相关权利、咨询和投诉渠道。",
    "enDesc": "Information on sexual harassment rights, enquiries and complaint routes.",
    "scope": "适用于有关反歧视法律覆盖的情形；不等同于刑事报案。",
    "enScope": "Applies within relevant anti-discrimination laws; not a criminal reporting channel.",
    "url": "https://www.eoc.org.hk/compass/en/",
    "checked": "2026-09-23"
  },
  {
    "id": "hk-police",
    "region": "香港特别行政区",
    "category": "报案渠道",
    "name": "香港警务处 · 性暴力求助信息",
    "enName": "Hong Kong Police · Sexual violence information",
    "desc": "警方公布的报案、调查程序及支援信息。",
    "enDesc": "Police information on reporting, investigation and support.",
    "scope": "香港特别行政区；网站介绍程序，不在本页面提交报案。",
    "enScope": "Hong Kong S.A.R; explains procedures, with no report submitted from this site.",
    "url": "https://www.police.gov.hk/svi/en/",
    "checked": "2026-09-23"
  },
  {
    "id": "us-rainn",
    "region": "美国",
    "category": "情绪支持",
    "name": "RAINN · 性侵犯支持热线",
    "enName": "RAINN · National Sexual Assault Hotline",
    "desc": "性暴力支持、当地服务以及法律和医疗转介。",
    "enDesc": "Sexual violence support and referrals to local, legal and medical resources.",
    "scope": "美国；披露前可先了解保密范围与报告义务。",
    "enScope": "United States; ask about confidentiality and reporting duties before disclosure.",
    "url": "https://rainn.org/help-and-healing/hotline/",
    "checked": "2026-09-23"
  },
  {
    "id": "us-eeoc",
    "region": "美国",
    "category": "法律咨询",
    "name": "EEOC · 职场性骚扰",
    "enName": "EEOC · Workplace sexual harassment",
    "desc": "职场性骚扰的联邦反歧视信息与投诉指引。",
    "enDesc": "Federal workplace discrimination information and complaint guidance.",
    "scope": "美国就业领域；适用资格与程序需核实，不是通用刑事报案入口。",
    "enScope": "US employment matters; verify eligibility and procedures. Not a general crime-reporting service.",
    "url": "https://www.eeoc.gov/sexual-harassment",
    "checked": "2026-09-23"
  },
  {
    "id": "uk-rc",
    "region": "英国",
    "category": "情绪支持",
    "name": "Rape Crisis England & Wales",
    "enName": "Rape Crisis England & Wales",
    "desc": "寻找性暴力支持与当地危机中心。",
    "enDesc": "Find sexual violence support and local crisis centres.",
    "scope": "英格兰与威尔士；各中心服务对象和条件可能不同。",
    "enScope": "England and Wales; eligibility varies by service and centre.",
    "url": "https://rapecrisis.org.uk/get-help/",
    "checked": "2026-09-23"
  },
  {
    "id": "uk-nhs",
    "region": "英国",
    "category": "医疗帮助",
    "name": "NHS · 性侵犯后的医疗帮助",
    "enName": "NHS · Help after rape and sexual assault",
    "desc": "了解医疗帮助与性侵犯转介中心（SARC）。",
    "enDesc": "Information on medical help and sexual assault referral centres (SARCs).",
    "scope": "英格兰 NHS 指引；其他地区请使用当地服务目录。",
    "enScope": "NHS England guidance; use local directories for other UK nations.",
    "url": "https://www.nhs.uk/live-well/sexual-health/help-after-rape-and-sexual-assault/",
    "checked": "2026-09-23"
  },
  {
    "id": "uk-scot",
    "region": "英国",
    "category": "报案渠道",
    "name": "Rape Crisis Scotland · 报案与法律",
    "enName": "Rape Crisis Scotland · Reporting and legal",
    "desc": "了解苏格兰报案流程以及支持与倡导服务。",
    "enDesc": "Learn about reporting in Scotland and available support and advocacy.",
    "scope": "苏格兰；此机构提供信息与支持，不是警方受理平台。",
    "enScope": "Scotland; information and support, not a police intake portal.",
    "url": "https://rapecrisisscotland.org.uk/help-reporting/",
    "checked": "2026-09-23"
  },
  {
    "id": "uk-ni",
    "region": "英国",
    "category": "情绪支持",
    "name": "nidirect · 性暴力服务目录",
    "enName": "nidirect · Sexual violence services",
    "desc": "北爱尔兰政府提供的性暴力报案与支持目录。",
    "enDesc": "Northern Ireland government directory of reporting and support resources.",
    "scope": "北爱尔兰；请查看各服务的具体要求。",
    "enScope": "Northern Ireland; check individual service requirements.",
    "url": "https://www.nidirect.gov.uk/articles/sexual-violence-directory-services",
    "checked": "2026-09-23"
  },
  {
    "id": "ca-help",
    "region": "加拿大",
    "category": "情绪支持",
    "name": "加拿大政府 · 寻求帮助",
    "enName": "Government of Canada · Get help now",
    "desc": "按省或地区查找性别暴力支持与性侵犯服务。",
    "enDesc": "Find gender-based violence and sexual assault support by province or territory.",
    "scope": "加拿大；服务由各省、地区和机构提供。",
    "enScope": "Canada; services are delivered by provinces, territories and providers.",
    "url": "https://www.canada.ca/en/women-gender-equality/gender-based-violence/get-help-now.html",
    "checked": "2026-09-23"
  },
  {
    "id": "ca-legal",
    "region": "加拿大",
    "category": "法律咨询",
    "name": "加拿大 · 各省与地区受害者服务",
    "enName": "Canada · Provincial and territorial victim services",
    "desc": "查询受害者服务及部分地区的独立法律咨询项目。",
    "enDesc": "Find victim services and independent legal advice programs in participating jurisdictions.",
    "scope": "加拿大；法律支持项目并非在所有地区均适用。",
    "enScope": "Canada; legal support programs are not available in every jurisdiction.",
    "url": "https://www.canada.ca/en/office-federal-ombudsperson-victims-crime/services-services/servicespt.html",
    "checked": "2026-09-23"
  },
  {
    "id": "au-respect",
    "region": "澳大利亚",
    "category": "情绪支持",
    "name": "1800RESPECT",
    "enName": "1800RESPECT",
    "desc": "家庭、家人及性暴力相关的咨询、信息与支持。",
    "enDesc": "Counselling, information and support for domestic, family and sexual violence.",
    "scope": "澳大利亚；请在官网查看联络方式及服务安排。",
    "enScope": "Australia; check the official site for contact options and availability.",
    "url": "https://1800respect.org.au/",
    "checked": "2026-09-23"
  },
  {
    "id": "au-rights",
    "region": "澳大利亚",
    "category": "法律咨询",
    "name": "澳大利亚人权委员会 · 就业投诉",
    "enName": "Australian Human Rights Commission · Employment complaints",
    "desc": "就业歧视及性骚扰相关的投诉信息。",
    "enDesc": "Complaint information on employment discrimination and sexual harassment.",
    "scope": "澳大利亚；需核实具体投诉适用性，不是刑事报案。",
    "enScope": "Australia; confirm complaint jurisdiction. Not criminal reporting.",
    "url": "https://www.humanrights.gov.au/our-work/complaint-information-service/complaints-about-discrimination-employment",
    "checked": "2026-09-23"
  },
  {
    "id": "sg-sacc",
    "region": "新加坡",
    "category": "情绪支持",
    "name": "AWARE · 性侵犯关怀中心",
    "enName": "AWARE · Sexual Assault Care Centre",
    "desc": "性侵犯支持服务及求助方式。",
    "enDesc": "Sexual assault support services and ways to get help.",
    "scope": "新加坡；请向中心确认服务范围、语言和预约要求。",
    "enScope": "Singapore; confirm scope, languages and appointments with the centre.",
    "url": "https://sacc.aware.org.sg/",
    "checked": "2026-09-23"
  },
  {
    "id": "jp-one",
    "region": "日本",
    "category": "医疗帮助",
    "name": "日本内阁府 · 性暴力一站式支援",
    "enName": "Japan Cabinet Office · One-stop support centres",
    "desc": "按地区查找性犯罪与性暴力一站式支援中心。",
    "enDesc": "Find regional one-stop centres for sexual crime and sexual violence support.",
    "scope": "日本各都道府县；具体服务与语言依中心而定。",
    "enScope": "Japan’s prefectures; services and languages vary by centre.",
    "url": "https://www.gender.go.jp/policy/no_violence/seibouryoku/consult.html",
    "checked": "2026-09-23"
  },
  {
    "id": "jp-police",
    "region": "日本",
    "category": "报案渠道",
    "name": "日本警察厅 · 性犯罪被害咨询",
    "enName": "Japan National Police Agency · Sexual crime consultation",
    "desc": "查询各都道府县警方的性犯罪咨询窗口。",
    "enDesc": "Find prefectural police consultation contacts for sexual crime.",
    "scope": "日本；提供咨询联系方式，不是本网站在线报案。",
    "enScope": "Japan; consultation contacts, not online reporting through this website.",
    "url": "https://www.npa.go.jp/higaisya/seihanzai/seihanzai.html",
    "checked": "2026-09-23"
  },
  {
    "id": "global-peach",
    "region": "global",
    "category": "资源目录",
    "name": "HotPeachPages · 国际支持目录",
    "enName": "HotPeachPages · International support directory",
    "desc": "按国家查找暴力与虐待相关支持机构。",
    "enDesc": "Find violence and abuse support organizations by country.",
    "scope": "全球目录；并非所有条目均专门处理性侵犯，需进一步核实。",
    "enScope": "Global directory; not every entry specializes in sexual assault. Verify individual listings.",
    "url": "https://www.hotpeachpages.net/",
    "checked": "2026-09-23"
  }
];
Object.assign(window.uiCopy,{
  "中国法律服务网 · 12348": "China Public Legal Service · 12348",
  "查询公共法律服务机构、办事指南与咨询入口。": "Find public legal service organizations, guidance and consultation options.",
  "中国大陆；具体法律援助条件需向当地机构确认。": "Mainland China; confirm local legal-aid eligibility with the provider.",
  "广东省妇联 · 12338 服务平台": "Guangdong Women’s Federation · 12338",
  "广东省妇女维权咨询服务入口。": "Entry point for women’s rights consultation in Guangdong.",
  "广东省；不是全国统一线上受理入口。": "Guangdong only; not a nationwide online intake service.",
  "风雨兰 · 性暴力支持": "RainLily · Sexual violence support",
  "性暴力支援、法律咨询及陪伴服务信息。": "Information on sexual violence support, legal consultation and accompaniment.",
  "主要面向年满 14 岁的女性性暴力经历者；其他服务条件请咨询机构。": "Primarily female survivors aged 14 or above; confirm eligibility for individual services.",
  "平等机会委员会 · COMPASS": "Equal Opportunities Commission · COMPASS",
  "性骚扰相关权利、咨询和投诉渠道。": "Information on sexual harassment rights, enquiries and complaint routes.",
  "适用于有关反歧视法律覆盖的情形；不等同于刑事报案。": "Applies within relevant anti-discrimination laws; not a criminal reporting channel.",
  "香港警务处 · 性暴力求助信息": "Hong Kong Police · Sexual violence information",
  "警方公布的报案、调查程序及支援信息。": "Police information on reporting, investigation and support.",
  "香港特别行政区；网站介绍程序，不在本页面提交报案。": "Hong Kong S.A.R; explains procedures, with no report submitted from this site.",
  "RAINN · 性侵犯支持热线": "RAINN · National Sexual Assault Hotline",
  "性暴力支持、当地服务以及法律和医疗转介。": "Sexual violence support and referrals to local, legal and medical resources.",
  "美国；披露前可先了解保密范围与报告义务。": "United States; ask about confidentiality and reporting duties before disclosure.",
  "EEOC · 职场性骚扰": "EEOC · Workplace sexual harassment",
  "职场性骚扰的联邦反歧视信息与投诉指引。": "Federal workplace discrimination information and complaint guidance.",
  "美国就业领域；适用资格与程序需核实，不是通用刑事报案入口。": "US employment matters; verify eligibility and procedures. Not a general crime-reporting service.",
  "Rape Crisis England & Wales": "Rape Crisis England & Wales",
  "寻找性暴力支持与当地危机中心。": "Find sexual violence support and local crisis centres.",
  "英格兰与威尔士；各中心服务对象和条件可能不同。": "England and Wales; eligibility varies by service and centre.",
  "NHS · 性侵犯后的医疗帮助": "NHS · Help after rape and sexual assault",
  "了解医疗帮助与性侵犯转介中心（SARC）。": "Information on medical help and sexual assault referral centres (SARCs).",
  "英格兰 NHS 指引；其他地区请使用当地服务目录。": "NHS England guidance; use local directories for other UK nations.",
  "Rape Crisis Scotland · 报案与法律": "Rape Crisis Scotland · Reporting and legal",
  "了解苏格兰报案流程以及支持与倡导服务。": "Learn about reporting in Scotland and available support and advocacy.",
  "苏格兰；此机构提供信息与支持，不是警方受理平台。": "Scotland; information and support, not a police intake portal.",
  "nidirect · 性暴力服务目录": "nidirect · Sexual violence services",
  "北爱尔兰政府提供的性暴力报案与支持目录。": "Northern Ireland government directory of reporting and support resources.",
  "北爱尔兰；请查看各服务的具体要求。": "Northern Ireland; check individual service requirements.",
  "加拿大政府 · 寻求帮助": "Government of Canada · Get help now",
  "按省或地区查找性别暴力支持与性侵犯服务。": "Find gender-based violence and sexual assault support by province or territory.",
  "加拿大；服务由各省、地区和机构提供。": "Canada; services are delivered by provinces, territories and providers.",
  "加拿大 · 各省与地区受害者服务": "Canada · Provincial and territorial victim services",
  "查询受害者服务及部分地区的独立法律咨询项目。": "Find victim services and independent legal advice programs in participating jurisdictions.",
  "加拿大；法律支持项目并非在所有地区均适用。": "Canada; legal support programs are not available in every jurisdiction.",
  "1800RESPECT": "1800RESPECT",
  "家庭、家人及性暴力相关的咨询、信息与支持。": "Counselling, information and support for domestic, family and sexual violence.",
  "澳大利亚；请在官网查看联络方式及服务安排。": "Australia; check the official site for contact options and availability.",
  "澳大利亚人权委员会 · 就业投诉": "Australian Human Rights Commission · Employment complaints",
  "就业歧视及性骚扰相关的投诉信息。": "Complaint information on employment discrimination and sexual harassment.",
  "澳大利亚；需核实具体投诉适用性，不是刑事报案。": "Australia; confirm complaint jurisdiction. Not criminal reporting.",
  "AWARE · 性侵犯关怀中心": "AWARE · Sexual Assault Care Centre",
  "性侵犯支持服务及求助方式。": "Sexual assault support services and ways to get help.",
  "新加坡；请向中心确认服务范围、语言和预约要求。": "Singapore; confirm scope, languages and appointments with the centre.",
  "日本内阁府 · 性暴力一站式支援": "Japan Cabinet Office · One-stop support centres",
  "按地区查找性犯罪与性暴力一站式支援中心。": "Find regional one-stop centres for sexual crime and sexual violence support.",
  "日本各都道府县；具体服务与语言依中心而定。": "Japan’s prefectures; services and languages vary by centre.",
  "日本警察厅 · 性犯罪被害咨询": "Japan National Police Agency · Sexual crime consultation",
  "查询各都道府县警方的性犯罪咨询窗口。": "Find prefectural police consultation contacts for sexual crime.",
  "日本；提供咨询联系方式，不是本网站在线报案。": "Japan; consultation contacts, not online reporting through this website.",
  "HotPeachPages · 国际支持目录": "HotPeachPages · International support directory",
  "按国家查找暴力与虐待相关支持机构。": "Find violence and abuse support organizations by country.",
  "全球目录；并非所有条目均专门处理性侵犯，需进一步核实。": "Global directory; not every entry specializes in sexual assault. Verify individual listings.",
  "按地区寻找维权与支持资源。": "Find rights and support resources by location.",
  "查找官方和专业机构入口。资源检索不需要提供经历或身份信息。": "Find government and specialist service entry points. No incident narrative or identity details are needed to search.",
  "搜索地区": "Resource location",
  "请选择地区": "Choose a location",
  "全球目录 / 其他地区": "Global directory / other regions",
  "使用当前所在地": "Use my current location",
  "使用事件发生地": "Use incident location",
  "报案渠道": "Reporting information",
  "资源目录": "Directories",
  "已收录资源": "Listed resources",
  "条匹配结果": "matching results",
  "官网信息核对": "Source reviewed",
  "适用范围": "Service scope",
  "查看机构官网 ↗": "Visit official site ↗",
  "准备咨询草稿 →": "Prepare an inquiry →",
  "查看范围与下一步": "Scope and next step",
  "全球目录": "Global directory",
  "资源详情": "Resource details",
  "这是人工整理的部分资源，不是全部机构名单。官网内容已核对，实际可用性、资格、语言与费用仍需向机构确认。": "This is a curated, partial directory, not a complete list. Sources were reviewed; confirm availability, eligibility, languages and fees with each provider.",
  "请先选择地区。暂时显示全球目录，不会自动推断你的所在地。": "Choose a location first. Only the global directory is shown for now; your location is not inferred.",
  "该地区暂无专门条目，以下为全球目录入口。请在目录中进一步查找。": "No dedicated entries are available for this location. Use the global directory below to continue your search.",
  "没有匹配的已收录资源": "No matching listed resources",
  "试试其他关键词或显示全部类别；没有结果不代表当地没有服务。": "Try other keywords or all categories. No results does not mean no services exist locally.",
  "来源已核对 · 非实时可用性保证": "Source reviewed · Availability not guaranteed",
  "打开官网不会自动发送你的记录。外部网站有自己的隐私政策。": "Opening the official site does not send your record. External sites have their own privacy policies.",
  "生成草稿不会联系这个机构；请自行核对接收渠道。": "Generating a draft does not contact this provider. Confirm its intake channel separately.",
  "先选择当前所在地，再使用这个选项。": "Select your current location first.",
  "先填写事件发生地，再使用这个选项。": "Enter the incident location first.",
  "地区无法精确匹配，已显示全球目录。": "Location could not be matched exactly. Showing the global directory.",
  "地区用于筛选已收录资源。跨境事件可在资源页切换检索地区。": "Location filters listed resources. For cross-border situations, switch the search location on the resource page.",
  "已更新地区，将筛选相应资源。": "Location updated. Resources will be filtered accordingly.",
  "资源链接是真实机构入口；草稿生成与提交仍为模拟。": "Resource links lead to real organizations; drafting and submission are still simulated.",
  "资源页提供真实机构链接，但不是完整名单或实时服务保证。": "The resource page links to real organizations, but is not exhaustive or a guarantee of availability.",
  "官方资源已接入 · 具体渠道适用性与时间要求仍需核实。": "Official resources available · Specific channel eligibility and time requirements still need verification.",
  "查看当地资源 →": "Explore local resources →"
});

window.resourceRegions=['中国大陆','香港特别行政区','美国','英国','加拿大','澳大利亚','新加坡','日本'];
window.normalizeResourceRegion=function(value){const v=String(value||'').trim().toLowerCase();const aliases={'china':'中国大陆','mainland china':'中国大陆','中国':'中国大陆','香港':'香港特别行政区','中国香港':'香港特别行政区','hong kong':'香港特别行政区','hong kong s.a.r':'香港特别行政区','hong kong s.a.r.':'香港特别行政区','us':'美国','usa':'美国','united states':'美国','uk':'英国','united kingdom':'英国','canada':'加拿大','australia':'澳大利亚','singapore':'新加坡','japan':'日本'};return resourceRegions.find(r=>r===value)||aliases[v]||'global';};
window.directorySearch=function({query='',category='全部',region=''}){const aliases={律师:'法律',报警:'报案',医院:'医疗',心理:'情绪',police:'report',lawyer:'legal',hospital:'medical',counseling:'support'};const q=aliases[query.trim().toLowerCase()]||query.trim().toLowerCase();const r=normalizeResourceRegion(region);return resourceDirectory.filter(x=>(x.region===r||x.region==='global')&&(category==='全部'||x.category===category)&&(!q||[x.name,x.enName,x.desc,x.enDesc,x.scope,x.enScope,x.category,uiCopy[x.category]].join(' ').toLowerCase().includes(q)));};
